'''
 a = 0, b=0, c=1 are the 1st three terms. All other terms in the Lucas sequence are generated by the sum of their 3 most recent predecessors. Write a program to generate the first n terms of a Lucas Sequence.
Input format:
The input containing an integer 'n' which denotes the given number
Output format:
Print the  'n' terms of the Lucas Sequence, separated by a single space. There are no leading or trailing spaces in the output.
Refer the sample output for formatting.
'''
def generate_lucas_sequence(n):
    if n == 1:
        return [0]
    elif n == 2:
        return [0, 0]
    elif n >= 3:
        sequence = [0, 0, 1]
        for i in range(3, n):
            next_term = sequence[i-1] + sequence[i-2] + sequence[i-3]
            sequence.append(next_term)
        return sequence
n = int(input("Enter the number of terms: "))
lucas_sequence = generate_lucas_sequence(n)
print(" ".join(map(str, lucas_sequence)))
'''
Enter the number of terms: 5
0 0 1 1 2
